export const GET_POSTS = 'GET-POSTS'
export const ADD_DEV = 'ADD-DEV'
export const SHUFFLE_ARR = 'SHUFFLE-ARR'
export const UPDATE_POST_ID = 'UPDATE-POST-ID'
export const DEL_POST = 'DEL-POST'
export const ADD_ACTION = 'ADD-ACTION'